version: '3'
services:
  filebeat:
    image: elastic/filebeat:7.0.1
    networks:
    - xnet
    ports:
    - ""
  logstash:
    image: elastic/logstash:7.0.1
    networks:
    - xnet
    ports:
    - "5044:5044"
    - "9600:9600"
volumes:
  logvolume01: {}
