version: '3'

services: 
  uaa:
    build:
      context: .
      args:
        JAR_FILE: "target/uaa.jar"
    ports:
      - "8080:8080"
  
  # mysql:
  #   image: mysql:latest
  #   ports:
  #   - "3306:3306"

  # redis:
  #   image: redis:latest
  #   ports:
  #   - "6369:6379"