filebeat.inputs:
- type: log
  paths:
    - /var/log/*.log
  document_type: "syslog"
  field:
    logsource: system
    logtype: syslog

output.logstash:
  hosts: ["logstash-7.0.1:5044"]
  
# filebeat.config:
#   modules:
#     path: ${path.config}/modules.d/*.yml
#     reload.enabled: false

# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

# processors:
# - add_cloud_metadata: ~